"""Investor display name -> Dataroma fund ID mapping (dataroma.com/m/m_activity.php?m=ID)."""

investors = {
    "AKO Capital": "AKO",
    "Alex Roepers": "AIM",
    "AltaRock Partners": "AP",
    "Bill & Melinda Gates Foundation Trust": "GFT",
    "Bill Ackman": "psc",
    "Bill Miller": "LMM",
    "Bill Nygren": "oaklx",
    "Bruce Berkowitz": "fairx",
    "Bryan Lawrence": "OCL",
    "Carl Icahn": "ic",
    "Charles Bobrinskoy": "ARFFX",
    "Chase Coleman": "TGM",
    "Chris Hohn": "tci",
    "Christopher Bloomstran": "SA",
    "Christopher Davis": "DAV",
    "Chuck Akre": "AC",
    "Clifford Sosin": "CAS",
    "Daniel Loeb": "tp",
    "David Abrams": "abc",
    "David Einhorn": "GLRE",
    "David Katz": "MAVFX",
    "David Rolfe": "WP",
    "David Tepper": "AM",
    "Dennis Hong": "SP",
    "Dodge & Cox": "DODGX",
    "Duan Yongping": "HH",
    "FPA Queens Road Small Cap Value Fund": "FPPTX",
    "First Eagle Investment Management": "FE",
    "Francis Chou": "ca",
    "Francois Rochon": "GC",
    "Glenn Greenberg": "CCM",
    "Glenn Welling": "ENG",
    "Greenhaven Associates": "GA",
    "Greg Alexander": "CM",
    "Guy Spier": "aq",
    "Harry Burn": "SSHFX",
    "Hillman Value Fund": "hcmax",
    "Howard Marks": "oc",
    "Jensen Investment Management": "JIM",
    "John Armitage": "EC",
    "John Rogers": "CAAPX",
    "Josh Tarasoff": "GLC",
    "Kahn Brothers Group": "KB",
    "Lee Ainslie": "mc",
    "Leon Cooperman": "oa",
    "Li Lu": "HC",
    "Lindsell Train": "LT",
    "Mairs & Power Growth Fund": "MPGFX",
    "Mason Hawkins": "LLPFX",
    "Meridian Contrarian Fund": "MVALX",
    "Michael Burry": "SAM",
    "Mohnish Pabrai": "PI",
    "Nelson Peltz": "TF",
    "Norbert Lou": "PC",
    "Pat Dorsey": "DA",
    "Polen Capital Management": "pcm",
    "Prem Watsa": "FFH",
    "Richard Pzena": "pzfvx",
    "Robert Olstein": "OFALX",
    "Robert Vinall": "RVC",
    "Ruane Cunniff": "SEQUX",
    "Samantha McLemoret": "PTNT",
    "Sarah Ketterer": "CAU",
    "Seth Klarman": "BAUPOST",
    "Stephen Mandel": "LPC",
    "Steven Romick": "FPACX",
    "Terry Smith": "FS",
    "Third Avenue Management": "TA",
    "Thomas Gayner": "MKL",
    "Thomas Russo": "GR",
    "Tom Bancroft": "MP",
    "Torray Funds": "T",
    "Triple Frond Partners": "TFP",
    "Tweedy Browne": "TWEBX",
    "Valley Forge": "VFC",
    "ValueAct Capital": "VA",
    "Viking Global Investors": "vg",
    "Wallace Weitz": "WVALX",
    "Warren Buffett": "BRK",
    "William Von Muefflingt": "cc",
    "Yacktman Asset Management": "YAM",
}
